### PR TITLE
Removed if condition on post.excerpt, Causing gallery post not to show

### PR DESCRIPTION
**Pull request by silverbux**
Example:
```
[gallery link="file" ids="7,8,9"] 
```
with the following gallery post excert will be null.

### CODE REVIEW

**Comment by silverbux** [comment]
+ added gallery css styles

**Comment by shprink** [comment]
what happened to the css?

**Comment by silverbux** [comment]
got some updates will just do another pull request for it

**Comment by shprink** [comment]
Sounds good, thanks for that :)

**Pull request merged**
