### PR TITLE
Set all nav title is center for android，successful running！

### PR DESCRIPTION
**Pull request by mingxia**
It looks much more comfortable.

### CODE REVIEW

**Comment by shprink** [comment]
This can be set via the ionic config. I would rather expose this via ```config.json``` if people want to overwrite the ionic behavior.

http://ionicframework.com/docs/api/provider/$ionicConfigProvider/

```
navBar.alignTitle(value)
```

**Comment by mingxia** [comment]
Just seen, it is a better solution. However, I still think the best will be centered as the default configuration, this would facilitate a lot of people. Let android, ios style unification

**Comment by shprink** [comment]
I want to keep ionic default configuration. They follow device standards so I do not want to change that. I am gonna give developers access to ionic configuration so they can change whatever they want from config.json

**Comment by shprink** [comment]
@mingxia I created https://github.com/shprink/wordpress-hybrid-client/issues/55 to do that.

If you wish to try please let me know. Otherwise I will do it soon

**Comment by mingxia** [comment]
I am busy something else, you do it. In addition “backButton.text(value) ” default is back, can according to language change?

**Comment by shprink** [comment]
Good thought! I am adding this to the ticket thanks.

**Comment by mingxia** [comment]
I see what you mean, it is very necessary to keep the standard of the state, but at the same time in the config. The json provides a customizable interface.

**Pull request closed without merging**
