### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by gonzaloplaza**
Added Spanish translation file (es.json)

### CODE REVIEW

**Comment by shprink** [comment]
That's awesome @gonzaloplaza ! Thanks very much, will merge soon

**Comment by shprink** [comment]
Merged thanks https://github.com/shprink/wordpress-hybrid-client/pull/51

**Comment by shprink** [comment]
@gonzaloplaza let me know if you have the app in the stores. I can feature them on the project webpage

**Comment by gonzaloplaza** [comment]
Not yet, i'm having troubles to run it into Windows, will add an issue with webpack, and blank page into emulator.

BTW: looks like there are some issues with charset into es.json file you merged

https://github.com/shprink/wordpress-hybrid-client/blob/develop/lib/translations/es.json

thanks!

**Pull request closed without merging**
