### PR TITLE
Change in dutch translations

### PR DESCRIPTION
**Pull request by xvilo**
While using the app I noticed some translations were not in context or inline with WordPress translations. Changed those!

### CODE REVIEW

**Comment by xvilo** [comment]
I think that didn't go too well right?

**Comment by shprink** [comment]
yes, something went wrong!

**Comment by shprink** [comment]
@xvilo a easy fix would be to edit the file directly on github since it is only few changes

**Comment by xvilo** [comment]
Is that possible? I'll look into that!

**Pull request closed without merging**
